### ISSUE TITLE
logitech c270 crush every time

### ISSUE THREAD

**Issue by phields** [RenderHeads/UnityPlugin-AVProLiveCamera#28] opened 2021-01-29 14:02 UTC
**Describe the bug**

**Your Setup (please complete the following information):**
 - Unity version: 2019.3.5
 - AVPro Live Camera version: 2.9.0
 - Operating system version: win10
 - Hardware/webcam model: logitech c270
 - Video mode (resolution, frame-rate, etc): null

**To Reproduce**

**Logs**
If applicable, add error logs to help explain your problem.
[error.log](https://github.com/RenderHeads/UnityPlugin-AVProLiveCamera/files/5894218/error.log)
**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

**Comment by phields** [comment] 2021-01-29 15:09
same issues on logitech c920

**Comment by AndrewRH** [comment] 2021-02-02 00:36
I am closing this as it's a duplicate of #23 - we will follow up in there

**Closed by AndrewRH** 2021-02-02 00:36 UTC
Labels: bug
